name: Lint

on:
  push:
  pull_request:

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: psf/black@stable
        with:
          version: '~=23.12'
  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Replace '3.x' with your desired Python version
      - name: Install poetry
        run: pip install poetry # You may need additional dependencies here
      - name: Install flarestack
        run: poetry install
      - name: Run mypy
        run: poetry run mypy  # Replace 'your_code_directory' with your actual code directory
